### ISSUE TITLE
migrations throwing errir

### ISSUE THREAD

**Issue by zhsolutions** [NikolaGavric94/nikolag-core#1]
This was installed along side your square plugin, i dont need this order tracking, not sure if it can be disabled, but the migrations throw erriors:

[Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB serv
  er version for the right syntax to use near 'unsigned not null, `first_name` varchar(191) null, `last_name` varchar(191) null' at line 1 (SQL: creat
  e table `nikolag_customers` (`id` int unsigned not null auto_increment primary key, `payment_service_id` int unsigned not null, `payment_service_typ
  e` varchar(25) unsigned not null, `first_name` varchar(191) null, `last_name` varchar(191) null, `company_name` varchar(191) null, `nickname` varcha
  r(191) null, `email` varchar(191) not null, `phone` varchar(191) null, `note` longtext null, `owner_id` varchar(191) null, `created_at` timestamp nu
  ll, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci)

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB serv
  er version for the right syntax to use near 'unsigned not null, `first_name` varchar(191) null, `last_name` varchar(191) null' at line 1

**Comment by NikolaGavric94** [comment]
First issue is resolved in [v1.0.2](https://github.com/NikolaGavric94/nikolag-core/releases/tag/v1.0.2) so make sure that you update it to that version and check if the files from the repo match your local copy in vendor.

Second issue is mentioned in laravel docs [here](https://laravel.com/docs/5.5/migrations#indexes). Scroll a bit down until u reach header **Index Lengths & MySQL / MariaDB**. That issue is appearing because you are using an older version of MySQL or MariaDB

**Comment by zhsolutions** [comment]
It is a fresh installation of MariaDB and the files match the latest version. Also, the fix mentioned within the Laravel docs, I had already applied.

**Comment by NikolaGavric94** [comment]
The build passed all the tests and I created a test project which included nikolag/square and this repo and migrations were fine, not giving me any error, can you try to clear composer cache and see if it works on a new fresh project?

**Comment by NikolaGavric94** [comment]
<img width="1280" alt="screen shot 2017-10-21 at 10 44 53" src="https://user-images.githubusercontent.com/12602403/31850078-0bbb592a-b64d-11e7-8e46-058ba0951578.png">

<img width="1280" alt="screen shot 2017-10-21 at 10 45 49" src="https://user-images.githubusercontent.com/12602403/31850092-1eba0ca6-b64d-11e7-9458-83dec55a0168.png">

**Comment by NikolaGavric94** [comment]
@zhsolutions have you resolved this issue?

**Comment by zhsolutions** [comment]
I will let you know maybe later today or tomorrow, as I stepped away for a bit.

I actually did a work around and just simply removed the migration so it would not run as I do not use or require the tables anyways, but ill check a fresh install of this shortly.

**Comment by NikolaGavric94** [comment]
@zhsolutions I'll be closing this issue, if you encounter it again, feel free to reopen this isue
